version: '3'
services:
  ausdeminternetkopiert:
    build: .
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ausdeminternetkopiert.rule=Host(`demo.traefik.kiki`)"
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true